module.exports = [
/* 00 */ { mnemonic: "unreachable", immediate: null },
/* 01 */ { mnemonic: "nop", immediate: null },
/* 02 */ { mnemonic: "block", immediate: null },
/* 03 */ { mnemonic: "loop", immediate: null },
/* 04 */ { mnemonic: "if", immediate: null },
/* 05 */ { mnemonic: "else", immediate: null },
/* 06 */ null,
/* 07 */ null,
/* 08 */ null,
/* 09 */ null,
/* 0A */ null,
/* 0B */ { mnemonic: "end", immediate: null },
/* 0C */ { mnemonic: "br", immediate: null },
/* 0D */ { mnemonic: "br_if", immediate: null },
/* 0E */ { mnemonic: "br_table", immediate: null },
/* 0F */ { mnemonic: "return", immediate: null },
/* 10 */ { mnemonic: "call", immediate: null },
/* 11 */ { mnemonic: "call_indirect", immediate: null },
/* 12 */ null,
/* 13 */ null,
/* 14 */ null,
/* 15 */ null,
/* 16 */ null,
/* 17 */ null,
/* 18 */ null,
/* 19 */ null,
/* 1A */ { mnemonic: "drop", immediate: null },
/* 1B */ { mnemonic: "select", immediate: null },
/* 1C */ null,
/* 1D */ null,
/* 1E */ null,
/* 1F */ null,
/* 20 */ { mnemonic: "get_local", immediate: null },
/* 21 */ { mnemonic: "set_local", immediate: null },
/* 22 */ { mnemonic: "tee_local", immediate: null },
/* 23 */ { mnemonic: "get_global", immediate: null },
/* 24 */ { mnemonic: "set_global", immediate: null },
/* 25 */ null,
/* 26 */ null,
/* 27 */ null,
/* 28 */ { mnemonic: "i32.load", immediate: null },
/* 29 */ { mnemonic: "i64.load", immediate: null },
/* 2A */ { mnemonic: "f32.load", immediate: null },
/* 2B */ { mnemonic: "f64.load", immediate: null },
/* 2C */ { mnemonic: "i32.load8_s", immediate: null },
/* 2D */ { mnemonic: "i32.load8_u", immediate: null },
/* 2E */ { mnemonic: "i32.load16_s", immediate: null },
/* 2F */ { mnemonic: "i32.load16_u", immediate: null },
/* 30 */ { mnemonic: "i64.load8_s", immediate: null },
/* 31 */ { mnemonic: "i64.load8_u", immediate: null },
/* 32 */ { mnemonic: "i64.load16_s", immediate: null },
/* 33 */ { mnemonic: "i64.load16_u", immediate: null },
/* 34 */ { mnemonic: "i64.load32_s", immediate: null },
/* 35 */ { mnemonic: "i64.load32_u", immediate: null },
/* 36 */ { mnemonic: "i32.store", immediate: null },
/* 37 */ { mnemonic: "i64.store", immediate: null },
/* 38 */ { mnemonic: "f32.store", immediate: null },
/* 39 */ { mnemonic: "f64.store", immediate: null },
/* 3A */ { mnemonic: "i32.store8", immediate: null },
/* 3B */ { mnemonic: "i32.store16", immediate: null },
/* 3C */ { mnemonic: "i64.store8", immediate: null },
/* 3D */ { mnemonic: "i64.store16", immediate: null },
/* 3E */ { mnemonic: "i64.store32", immediate: null },
/* 3F */ { mnemonic: "current_memory", immediate: null },
/* 40 */ { mnemonic: "grow_memory", immediate: null },
/* 41 */ { mnemonic: "i32.const", immediate: null },
/* 42 */ { mnemonic: "i64.const", immediate: null },
/* 43 */ { mnemonic: "f32.const", immediate: null },
/* 44 */ { mnemonic: "f64.const", immediate: null },
/* 45 */ { mnemonic: "i32.eqz", immediate: null },
/* 46 */ { mnemonic: "i32.eq", immediate: null },
/* 47 */ { mnemonic: "i32.ne", immediate: null },
/* 48 */ { mnemonic: "i32.lt_s", immediate: null },
/* 49 */ { mnemonic: "i32.lt_u", immediate: null },
/* 4A */ { mnemonic: "i32.gt_s", immediate: null },
/* 4B */ { mnemonic: "i32.gt_u", immediate: null },
/* 4C */ { mnemonic: "i32.le_s", immediate: null },
/* 4D */ { mnemonic: "i32.le_u", immediate: null },
/* 4E */ { mnemonic: "i32.ge_s", immediate: null },
/* 4F */ { mnemonic: "i32.ge_u", immediate: null },
/* 50 */ { mnemonic: "i64.eqz", immediate: null },
/* 51 */ { mnemonic: "i64.eq", immediate: null },
/* 52 */ { mnemonic: "i64.ne", immediate: null },
/* 53 */ { mnemonic: "i64.lt_s", immediate: null },
/* 54 */ { mnemonic: "i64.lt_u", immediate: null },
/* 55 */ { mnemonic: "i64.gt_s", immediate: null },
/* 56 */ { mnemonic: "i64.gt_u", immediate: null },
/* 57 */ { mnemonic: "i64.le_s", immediate: null },
/* 58 */ { mnemonic: "i64.le_u", immediate: null },
/* 59 */ { mnemonic: "i64.ge_s", immediate: null },
/* 5A */ { mnemonic: "i64.ge_u", immediate: null },
/* 5B */ { mnemonic: "f32.eq", immediate: null },
/* 5C */ { mnemonic: "f32.ne", immediate: null },
/* 5D */ { mnemonic: "f32.lt", immediate: null },
/* 5E */ { mnemonic: "f32.gt", immediate: null },
/* 5F */ { mnemonic: "f32.le", immediate: null },
/* 60 */ { mnemonic: "f32.ge", immediate: null },
/* 61 */ { mnemonic: "f64.eq", immediate: null },
/* 62 */ { mnemonic: "f64.ne", immediate: null },
/* 63 */ { mnemonic: "f64.lt", immediate: null },
/* 64 */ { mnemonic: "f64.gt", immediate: null },
/* 65 */ { mnemonic: "f64.le", immediate: null },
/* 66 */ { mnemonic: "f64.ge", immediate: null },
/* 67 */ { mnemonic: "i32.clz", immediate: null },
/* 68 */ { mnemonic: "i32.ctz", immediate: null },
/* 69 */ { mnemonic: "i32.popcnt", immediate: null },
/* 6A */ { mnemonic: "i32.add", immediate: null },
/* 6B */ { mnemonic: "i32.sub", immediate: null },
/* 6C */ { mnemonic: "i32.mul", immediate: null },
/* 6D */ { mnemonic: "i32.div_s", immediate: null },
/* 6E */ { mnemonic: "i32.div_u", immediate: null },
/* 6F */ { mnemonic: "i32.rem_s", immediate: null },
/* 70 */ { mnemonic: "i32.rem_u", immediate: null },
/* 71 */ { mnemonic: "i32.and", immediate: null },
/* 72 */ { mnemonic: "i32.or", immediate: null },
/* 73 */ { mnemonic: "i32.xor", immediate: null },
/* 74 */ { mnemonic: "i32.shl", immediate: null },
/* 75 */ { mnemonic: "i32.shr_s", immediate: null },
/* 76 */ { mnemonic: "i32.shr_u", immediate: null },
/* 77 */ { mnemonic: "i32.rotl", immediate: null },
/* 78 */ { mnemonic: "i32.rotr", immediate: null },
/* 79 */ { mnemonic: "i64.clz", immediate: null },
/* 7A */ { mnemonic: "i64.ctz", immediate: null },
/* 7B */ { mnemonic: "i64.popcnt", immediate: null },
/* 7C */ { mnemonic: "i64.add", immediate: null },
/* 7D */ { mnemonic: "i64.sub", immediate: null },
/* 7E */ { mnemonic: "i64.mul", immediate: null },
/* 7F */ { mnemonic: "i64.div_s", immediate: null },
/* 80 */ { mnemonic: "i64.div_u", immediate: null },
/* 81 */ { mnemonic: "i64.rem_s", immediate: null },
/* 82 */ { mnemonic: "i64.rem_u", immediate: null },
/* 83 */ { mnemonic: "i64.and", immediate: null },
/* 84 */ { mnemonic: "i64.or", immediate: null },
/* 85 */ { mnemonic: "i64.xor", immediate: null },
/* 86 */ { mnemonic: "i64.shl", immediate: null },
/* 87 */ { mnemonic: "i64.shr_s", immediate: null },
/* 88 */ { mnemonic: "i64.shr_u", immediate: null },
/* 89 */ { mnemonic: "i64.rotl", immediate: null },
/* 8A */ { mnemonic: "i64.rotr", immediate: null },
/* 8B */ { mnemonic: "f32.abs", immediate: null },
/* 8C */ { mnemonic: "f32.neg", immediate: null },
/* 8D */ { mnemonic: "f32.ceil", immediate: null },
/* 8E */ { mnemonic: "f32.floor", immediate: null },
/* 8F */ { mnemonic: "f32.trunc", immediate: null },
/* 90 */ { mnemonic: "f32.nearest", immediate: null },
/* 91 */ { mnemonic: "f32.sqrt", immediate: null },
/* 92 */ { mnemonic: "f32.add", immediate: null },
/* 93 */ { mnemonic: "f32.sub", immediate: null },
/* 94 */ { mnemonic: "f32.mul", immediate: null },
/* 95 */ { mnemonic: "f32.div", immediate: null },
/* 96 */ { mnemonic: "f32.min", immediate: null },
/* 97 */ { mnemonic: "f32.max", immediate: null },
/* 98 */ { mnemonic: "f32.copysign", immediate: null },
/* 99 */ { mnemonic: "f64.abs", immediate: null },
/* 9A */ { mnemonic: "f64.neg", immediate: null },
/* 9B */ { mnemonic: "f64.ceil", immediate: null },
/* 9C */ { mnemonic: "f64.floor", immediate: null },
/* 9D */ { mnemonic: "f64.trunc", immediate: null },
/* 9E */ { mnemonic: "f64.nearest", immediate: null },
/* 9F */ { mnemonic: "f64.sqrt", immediate: null },
/* A0 */ { mnemonic: "f64.add", immediate: null },
/* A1 */ { mnemonic: "f64.sub", immediate: null },
/* A2 */ { mnemonic: "f64.mul", immediate: null },
/* A3 */ { mnemonic: "f64.div", immediate: null },
/* A4 */ { mnemonic: "f64.min", immediate: null },
/* A5 */ { mnemonic: "f64.max", immediate: null },
/* A6 */ { mnemonic: "f64.copysign", immediate: null },
/* A7 */ { mnemonic: "i32.wrap/i64", immediate: null },
/* A8 */ { mnemonic: "i32.trunc_s/f32", immediate: null },
/* A9 */ { mnemonic: "i32.trunc_u/f32", immediate: null },
/* AA */ { mnemonic: "i32.trunc_s/f64", immediate: null },
/* AB */ { mnemonic: "i32.trunc_u/f64", immediate: null },
/* AC */ { mnemonic: "i64.extend_s/i32", immediate: null },
/* AD */ { mnemonic: "i64.extend_u/i32", immediate: null },
/* AE */ { mnemonic: "i64.trunc_s/f32", immediate: null },
/* AF */ { mnemonic: "i64.trunc_u/f32", immediate: null },
/* B0 */ { mnemonic: "i64.trunc_s/f64", immediate: null },
/* B1 */ { mnemonic: "i64.trunc_s/f64", immediate: null },
/* B2 */ { mnemonic: "f32.convert_s/i32", immediate: null },
/* B3 */ { mnemonic: "f32.convert_u/i32", immediate: null },
/* B4 */ { mnemonic: "f32.convert_s/i64", immediate: null },
/* B5 */ { mnemonic: "f32.convert_u/i64", immediate: null },
/* B6 */ { mnemonic: "f32.demote/i32", immediate: null },
/* B7 */ { mnemonic: "f64.convert_s/i32", immediate: null },
/* B8 */ { mnemonic: "f64.convert_u/i32", immediate: null },
/* B9 */ { mnemonic: "f64.convert_s/i64", immediate: null },
/* BA */ { mnemonic: "f64.convert_u/i64", immediate: null },
/* BB */ { mnemonic: "f64.promote/f32", immediate: null },
/* BC */ { mnemonic: "i32.reinterpret/f32", immediate: null },
/* BD */ { mnemonic: "i64.reinterpret/f64", immediate: null },
/* BE */ { mnemonic: "f32.reinterpret/i32", immediate: null },
/* BF */ { mnemonic: "f64.reinterpret/i64", immediate: null },
/* C0 */ null,
/* C1 */ null,
/* C2 */ null,
/* C3 */ null,
/* C4 */ null,
/* C5 */ null,
/* C6 */ null,
/* C7 */ null,
/* C8 */ null,
/* C9 */ null,
/* CA */ null,
/* CB */ null,
/* CC */ null,
/* CD */ null,
/* CE */ null,
/* CF */ null,
/* D0 */ null,
/* D1 */ null,
/* D2 */ null,
/* D3 */ null,
/* D4 */ null,
/* D5 */ null,
/* D6 */ null,
/* D7 */ null,
/* D8 */ null,
/* D9 */ null,
/* DA */ null,
/* DB */ null,
/* DC */ null,
/* DD */ null,
/* DE */ null,
/* DF */ null,
/* E0 */ null,
/* E1 */ null,
/* E2 */ null,
/* E3 */ null,
/* E4 */ null,
/* E5 */ null,
/* E6 */ null,
/* E7 */ null,
/* E8 */ null,
/* E9 */ null,
/* EA */ null,
/* EB */ null,
/* EC */ null,
/* ED */ null,
/* EE */ null,
/* EF */ null,
/* F0 */ null,
/* F1 */ null,
/* F2 */ null,
/* F3 */ null,
/* F4 */ null,
/* F5 */ null,
/* F6 */ null,
/* F7 */ null,
/* F8 */ null,
/* F9 */ null,
/* FA */ null,
/* FB */ null,
/* FC */ null,
/* FD */ null,
/* FE */ null,
/* FF */ null
];